---
- name: Install screen and pip
  apt:
    name:
      - python3-pip
      - screen
    state: present

- name: Install esptool
  pip:
    name: esptool
    state: present

#- name: Set wifi config
#  copy:
#    dest: /etc/wpa_supplicant/wpa_supplicant.conf
#    content: |
#      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
#      update_config=1
#      country=US
#      network={
#          ssid="{{ wifi_ssid }}"
#          psk="{{ wifi_password }}"
#      }
#    mode: u=rw,go=
#  register: set_wifi_config

- name: Enable persistent logging
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Storage
    value: persistent
    no_extra_spaces: yes
  register: config_journald

- name: Restart journald if needed
  systemd:
    name: systemd-journald.service
    state: restarted
  when: config_journald.changed
