set(ENV{IDF_PATH} $ENV{HOME}/.platformio/packages/framework-espidf)
set(ENV{PATH} "$ENV{HOME}/.platformio/penv/bin:$ENV{HOME}/.platformio/packages/toolchain-xtensa32/bin:$ENV{PATH}")

add_definitions(-DSDKCONFIG=sdkconfig.clion)

add_custom_target(
	Production ALL
	COMMAND platformio -c clion run "$<$<NOT:$<CONFIG:All>>:-e${CMAKE_BUILD_TYPE}>"
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)
add_custom_target(
	Debug ALL
	COMMAND platformio -c clion run --environment dev_chancey --target debug "$<$<NOT:$<CONFIG:All>>:-e${CMAKE_BUILD_TYPE}>"
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)

# TODO This is almost certainly not going to work on other machines but I have put it in the repo for example
# TODO Pull these values from `platformio project idedata`
include_directories(
	"$ENV{HOME}/.platformio/lib"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/cores/esp32"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/ArduinoOTA/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/AsyncUDP/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/BLE/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/BluetoothSerial/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/DNSServer/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/EEPROM/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/ESP32/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/ESPmDNS/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/FFat/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/FS/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/HTTPClient/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/HTTPUpdate/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/NetBIOS/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/Preferences/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/SD/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/SD_MMC/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/SPI/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/SPIFFS/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/SimpleBLE/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/Ticker/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/Update/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/WebServer/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/WiFi/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/WiFiClientSecure/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/libraries/Wire/src"
	"$ENV{HOME}/.platformio/packages/framework-arduinoespressif32-src-c69fc9322995db5694e2741d307d9723/variants/esp32"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/app_trace/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/app_update/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/asio/asio/asio/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/asio/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/bootloader_support/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/coap/libcoap/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/coap/libcoap/include/coap2"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/coap/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/coap/port/include/coap"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/console"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/driver/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/efuse/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/efuse/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp-tls"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_adc_cal/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_common/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_eth/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_event/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_gdbstub/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_http_client/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_http_server/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_https_ota/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_local_ctrl/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_ringbuf/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_rom/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_websocket_client/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_wifi/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/esp_wifi/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/espcoredump/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/expat/expat/expat/lib"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/expat/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/fatfs/diskio"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/fatfs/src"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/fatfs/vfs"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/freemodbus/common/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/freertos/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/heap/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/idf_test/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/jsmn/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/json/cJSON"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/libsodium/libsodium/src/libsodium/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/libsodium/port_include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/log/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/lwip/include/apps"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/lwip/include/apps/sntp"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/lwip/lwip/src/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/lwip/port/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/lwip/port/esp32/include/arch"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/mbedtls/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/mdns/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/mqtt/esp-mqtt/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/newlib/platform_include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/nghttp/nghttp2/lib/includes"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/nghttp/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/nvs_flash/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/openssl/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/protobuf-c/protobuf-c"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/protocomm/include/common"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/protocomm/include/security"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/protocomm/include/transports"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/pthread/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/sdmmc/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/soc/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/soc/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/spi_flash/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/spiffs/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/tcp_transport/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/tcpip_adapter/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/ulp/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/unity/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/unity/unity/src"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/vfs/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/wear_levelling/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/wifi_provisioning/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/wpa_supplicant/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/wpa_supplicant/include/esp_supplicant"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/wpa_supplicant/port/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/xtensa/esp32/include"
	"$ENV{HOME}/.platformio/packages/framework-espidf/components/xtensa/include"
	"$ENV{HOME}/.platformio/packages/tool-unity"
	"$ENV{HOME}/.platformio/packages/toolchain-xtensa32/lib/gcc/xtensa-esp32-elf/8.2.0/include"
	"$ENV{HOME}/.platformio/packages/toolchain-xtensa32/lib/gcc/xtensa-esp32-elf/8.2.0/include-fixed"
	"$ENV{HOME}/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include"
	"$ENV{HOME}/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/8.2.0"
	"$ENV{HOME}/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/8.2.0/xtensa-esp32-elf"
	"../.pio/build/prod/config"
	"../.pio/libdeps/prod"
	"../.pio/libdeps/prod/Adafruit MPRLS Library"
	"../.pio/libdeps/prod/Adafruit MPRLS Library"
	"../.pio/libdeps/prod/Adafruit Unified Sensor"
	"../include"
	"../lib"
	"../src"
	"../src"
	"../vendor/RxCpp/Rx/v2/src"
	"../vendor/lv_port_esp32/components/lvgl"
	"../vendor/lv_port_esp32/components/lvgl/lvgl"
	"../vendor/lv_port_esp32/components/lvgl_esp32_drivers"
	"../vendor/lv_port_esp32/components/lvgl_esp32_drivers/lvgl_tft"
)